import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { Heading, Link, Text, Code, Flex, Box, Image } from "@chakra-ui/react";
import THE_NEWS_API_KEY from "../keys/keys";
const dayjs = require("dayjs");
var relativeTime = require("dayjs/plugin/relativeTime");
dayjs.extend(relativeTime);
// import * as dayjs from 'dayjs'

const Home: NextPage = (props: any) => {
  // let teste = posts;
  console.log(props);
  return (
    <Flex w="100%" h="100%" justify="center">
      <Head>
        <title>Teste</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1" size="2xl" mb="2" mt="20">
          <Link color="spacejelly" href="https://nextjs.org">
            Blog do Jae
          </Link>
        </Heading>

        <Text fontSize="xl" mt="2">
          Seja bem-vindo ao <Code>jae.js</Code>
        </Text>

        <Flex
          flexWrap="wrap"
          alignItems="center"
          justifyContent="center"
          maxW="800px"
          mt="10"
        >
          {props?.posts?.map((e: any, key: number) => {
            let publishedAt = dayjs(e.publishedAt).fromNow();
            publishedAt = publishedAt
              .replace("hours", "horas")
              .replace("ago", "atrás");
            return (
              <Box
                key={key}
                as="a"
                href={e.url}
                // p="6"
                m="4"
                // borderWidth="1px"
                rounded="lg"
                flexBasis={["auto", "45%"]}
                overflow="hidden"
              >
                <Box overflow="hidden" maxH="150">
                  <Image
                    src={
                      e.urlToImage ||
                      "https://s2.glbimg.com/oFncdoGSUg7AKnHTYfvO9sDFiCI=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2021/P/A/ZMFshYTXeKZ4ddaZGx0w/71q4bbqanvl.-ac-sl1500-.jpg"
                    }
                    alt={`Imagem do post: ${e.title}`}
                    // maxH="200"
                    w="100%"
                  />
                </Box>

                <Box p={6} backgroundColor="#333">
                  <Heading as="h3" size="lg" mb="2" noOfLines={2}>
                    Teste {e.title} &rarr;
                  </Heading>
                  <Text fontSize="lg" noOfLines={1}>
                    {e.description}
                  </Text>
                  <Flex mt="6">
                    <Text as="sup">{e.source.name}</Text>
                    <Text as="sup">{publishedAt}</Text>
                  </Flex>
                </Box>
              </Box>
            );
          })}
        </Flex>
      </main>
    </Flex>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?country=br&category=technology&apiKey=${THE_NEWS_API_KEY}`
  );
  const { articles } = await res.json();

  return {
    props: {
      posts: articles,
    },
  };
};

export default Home;
