import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { Heading, Link, Flex } from "@chakra-ui/react";
import THE_NEWS_API_KEY from "../keys/keys";
const dayjs = require("dayjs");
var relativeTime = require("dayjs/plugin/relativeTime");
dayjs.extend(relativeTime);
import HotTopics from "../components/hotTopics";
import LatestNews from "../components/latestNews";

const Home: NextPage = (props: any) => {
  return (
    <>
      <Flex w="100%" h="100%" justify="center">
        <Head>
          <title>Blog do Jae</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Heading as="h1" size="2xl" mb="2" mt="20">
            <Link color="spacejelly" href="https://nextjs.org">
              Blog do Jae
            </Link>
          </Heading>
          <HotTopics posts={props.posts} />
          <LatestNews posts={props.posts} />
        </main>
      </Flex>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?country=br&apiKey=${THE_NEWS_API_KEY}`
  );
  const { articles } = await res.json();

  return {
    props: {
      posts: articles,
    },
  };
};

export default Home;
